### ISSUE TITLE
Add anchors to headings in docs

### ISSUE THREAD

**Issue by hrushikeshrv** [hrushikeshrv/mjxgui#15]
We need to add anchor tags to all headings in the documentation, and change the font family to a monospace font for certain headings in the API section.

**Comment by nishant-giri** [comment]
@hrushikeshrv, could you kindly assign me this task?

**Comment by nishant-giri** [comment]
Thank you, @hrushikeshrv for assigning me the task. I would make the required changes soon.

**Comment by hrushikeshrv** [comment]
@nishant-giri any updates?
