### ISSUE TITLE
Dynamically construct editor UI instead of hardcoding

### ISSUE THREAD

**Issue by hrushikeshrv** [hrushikeshrv/mjxgui#18]
Currently, the editor window's HTML is hardcoded in [ui.js](https://github.com/hrushikeshrv/mjxgui/blob/1c61ba2f85fb436d95162ee0b9013fe8b3601a4f/src/modules/ui.js#L212) , which makes it hard to change and test. Instead, we can construct the same HTML dynamically in the same function and append it to the DOM

**Comment by balogun14** [comment]
I will like to handle this but I don’t think I understand what I’m meant to do

**Comment by hrushikeshrv** [comment]
Hi @balogun14, thanks for your interest!

So the way that MJXGUI works is that when an HTML element is clicked, the MJXGUI editor window is shown on screen. The HTML code for this editor window is currently hardcoded as a string [at this line in ui.js](https://github.com/hrushikeshrv/mjxgui/blob/1c61ba2f85fb436d95162ee0b9013fe8b3601a4f/src/modules/ui.js#L212). This line is just the minified version of the HTML code in [editor.html](https://github.com/hrushikeshrv/mjxgui/blob/main/src/modules/editor.html). This HTML code defines how the MJXGUI editor window looks.

If you observe carefully, you will notice that lines 36-84 are very similar, and so are lines 87-139 and lines 142-168. So instead of hardcoding this HTML as a string, we should generate this HTML using JavaScript. 

For example, we could generate lines 36 to 84 using the following code snippet -

```javascript
const tab1 = document.createElement('div');
tab1.classList.add('mjxgui_tab');
tab1.dataset.tab = '1';
tab1.style.display = 'flex';

const letters = {
    'Alpha': '&Alpha;',
    'Beta': '&Beta;',
    'Gamma': '&Gamma;',
    // And so on for all Greek letters
};

for (let key in letters) {
    tab1.innerHTML += `<span class="mjxgui-btn mjxgui-greek-letter" data-latex-data="${key}">${letters[key]}</span>`;
}
```

Once we have generated this HTML, and stored it in the `tab1` variable, we can append it to the editor window by doing 

```javascript
editorDiv.appendChild(tab1);
```

Similarly, we can generate the HTML for the other repeated lines. This will reduce the payload size of the library considerably and also make it easier to maintain and add more functionality to. Hope that clarification helped. If you have any more questions please don't hesitate to ask.

Let me know if you feel comfortable enough with this task to take this on! If you're unsure, I can also guide you with the implementation.

**Comment by balogun14** [comment]
I will like to take this as a challenge but I think I am going to need some guidance

**Comment by balogun14** [comment]
So do you want me to create variables for this and append them

**Comment by hrushikeshrv** [comment]
Yes, that would be one way to start. Once you create a pull request I will be able to tell you what you should do.

**Comment by hrushikeshrv** [comment]
Great, I'll assign it to you.

**Comment by balogun14** [comment]
@hrushikeshrv i created a pr now
