### ISSUE TITLE
Improve editor UI

### ISSUE THREAD

**Issue by hrushikeshrv** [hrushikeshrv/mjxgui#2]
The editor UI currently has buttons for users to enter mathematical functions (like sin, cos, and more), that are rendered as buttons and contain text that is typeset using MathJax. This leads to a poor UX when users click on them and then use the arrow keys to navigate, as this brings the typeset button into focus.

We could replace them with SVGs or images so that this doesn't happen anymore. This will involve editing the editor HTML described in the [src/modules/ui.js](https://github.com/hrushikeshrv/mjxgui/blob/306bd0f2e005bad21ba173882627d5d94b81edee/src/modules/ui.js#L447) and replacing all text enclosed between '$' with SVGs, images, or something similar.

**Comment by srijit2002** [comment]
I want to take this issue. Can you please assign it to me?

**Comment by hrushikeshrv** [comment]
Sure, if you need any help with the internal working of the API or anything else feel free to ask.

**Comment by srijit2002** [comment]
@hrushikeshrv thanks a lot. I will open a pull request soon

**Comment by srijit2002** [comment]
@hrushikeshrv I have not found any consistent icon set on the internet. So, I think I need to create it myself in photoshop. Can I do it?

**Comment by hrushikeshrv** [comment]
Yeah sure. If you go to [the example](https://hrus.in/mjxgui/examples/basic-example.html) and take a look at the buttons in question (under the Functions tab), you'll see that we need to replace the buttons for the following functions -

- double integral
- limit
- square root
- nth root
- subscript
- superscript
- subscript & superscript
- fraction
- all the trigonometric functions

These buttons are described in the [editor HTML](https://github.com/hrushikeshrv/mjxgui/blob/306bd0f2e005bad21ba173882627d5d94b81edee/src/modules/ui.js#L438) on line 438 and lines 447 to 462. If you can create SVGs for these functions and replace the '$ \func $' string with them, that would work. SVGs would be better than images to keep our payload size low. 

But try to find inbuilt HTML character codes/ASCII math char codes before designing an SVG. I've just found that the double integral sign can be replaced by the hex code &amp;#8748; or &amp;Int; so we could replace the '$ \\iint{} $' on line 438 with &amp;#8748; and achieve the same result (&Int;). I doubt we can do the same with the other buttons, though.

**Comment by srijit2002** [comment]
@hrushikeshrv ok got it. But why changes are not showing in my local environment? I have opened basic-example.html file in live-server

**Comment by hrushikeshrv** [comment]
Which changes do you mean? If you mean the double integral sign, I haven't changed the code yet. I just found the hex code for it by googling it and tried it once by inspecting the editor HTML in my browser.

**Comment by srijit2002** [comment]
@hrushikeshrv I mean I have cloned the repository and changed the double integral sign by myself. But I did not see any changes.Changes are not reflecting in my browser.Can you please explain the process of setting the dev environment.I think ,I have made mistake in setting up the dev environment

**Comment by hrushikeshrv** [comment]
@srijit2002 that's because the examples use a different build of the library (check the linked script in the head). For the purpose of development, remove the script that uses the example build and link the expression-backend, controller, and ui scripts from the src folder separately and in that order.

**Comment by srijit2002** [comment]
@hrushikeshrv thanks for your clear explanations. 

# To resolve the issues I have done the following steps-
1) I have made all the svg icons and put those in a separate folder called `assets` in the root of the directory.
2) And after that I have put all of those icons inside it and used them in `ui.js` using the `image` tag.

I will open a pull request on 1st october :-)

Do you have any suggestions or do I need to make any changes to the file structure? Please let me know :-)

**Comment by hrushikeshrv** [comment]
Sounds good. Have you used/tested it yet?
I think one change we may need to make is to minify the SVG source of the SVGs you created and hard code it into the editor UI, but we can do that once you open a pull request and I review it.
