### ISSUE TITLE
Document how to customize editor CSS

### ISSUE THREAD

**Issue by hrushikeshrv** [hrushikeshrv/mjxgui#20]
The editor window has some classes and ids  associated with its elements that can be used by users to apply custom styles to the window. These selectors should be documented and we should provide a few small examples on how to customize the styles for the editor window.

**Comment by Myworld21** [comment]
I am interested in this documentation task. Can you assign me this issue?

**Comment by hrushikeshrv** [comment]
Sure, thanks! If you need any info or clarification feel free to reach out to me. 😄
