### ISSUE TITLE
Run callback function when enter key is pressed

### ISSUE THREAD

**Issue by hrushikeshrv** [hrushikeshrv/mjxgui#21]
When the enter key is pressed, we should close the editor window and run the success callback function. Currently, nothing happens. This will require modifying the `Cursor` class's `keyPress()` method.

**Comment by Jony-Jas** [comment]
I would take this on 👍

**Comment by hrushikeshrv** [comment]
Great, thanks! I'll assign this to you. Let me know in case you have any questions!

**Comment by Shivansh175** [comment]
can i also work on it?

**Comment by mohak34** [comment]
I had a doubt in this, in the callback function how can we close the editor using the enter key ?

**Comment by hrushikeshrv** [comment]
Hi, @mohak34 I'm not sure I understand your question. Do you mean while using MJXGUI's API? Currently nothing happens when the enter key is pressed, but after this issue is fixed, the editor will close automatically after the enter key is pressed, and the callback function will be run.

**Comment by Jony-Jas** [comment]
Update: I have completed the functionality and will send PR by Oct 1
