### ISSUE TITLE
Rewrite docs to clarify installation and usage

### ISSUE THREAD

**Issue by hrushikeshrv** [hrushikeshrv/mjxgui#22]
Currently the docs are written in a very verbose language. We should make the language clearer and shorter so it is easier for new users to get started using MJXGUI. In particular, we should make the `Usage` section clearer by showing a small demo first and then explaining the usage in text.

**Comment by Akshith-S** [comment]
Hi @hrushikeshrv , 
I would like to work on this issue! I'm new to Open Source and I've no idea about MJXGUI but would like to learn about it and make meaningful contributions for the betterment of your project.

**Comment by hrushikeshrv** [comment]
Hi @Akshith-S, Welcome!
So the issue is to clarify the wording of the `Usage` section in the docs. The docs are stored in the `docs/index.html` file in the repository. We want to rearrange the information in the `Usage` section so that we first show a simple example of how to use MJXGUI, which is the code block at line 155. We should move that to the top of the section and then write the rest of the text.

Once that is done we can look at changing the wording of the section to make it clearer (if necessary).

In order to get an understanding of what MJXGUI is and the features it offers, you can take a look at the [features](https://hrus.in/mjxgui/#features-head) and [introduction](https://hrus.in/mjxgui/#what-head) section of the docs. It would also be helpful to try out the [examples](https://hrus.in/mjxgui/#examples-head). If you need any more info or clarification, please feel free to reach out to me!

Again, thanks for volunteering and all the best for Hacktoberfest!
