### ISSUE TITLE
Add method to hide and show editor window

### ISSUE THREAD

**Issue by hrushikeshrv** [hrushikeshrv/mjxgui#23]
Currently the editor window is only shown if a particular HTML element is clicked. We should add a method that can be called at any time to show the editor window and a corresponding method to hide the editor window, document those methods, and use them while adding a click listener to the respective HTML element.

**Comment by zainbinfurqan** [comment]
Hi. @hrushikeshrv can i worked on it?

**Comment by hrushikeshrv** [comment]
Hi @zainbinfurqan, sure! So there already exists a method to show the editor window (`MJXGUI.showUI()`), we will just need to add a method to hide the editor window, maybe called `MJXGUI.hideUI()`.

This method should just remove the style attribute of the editor window and set the `visible` attribute in the dataset to `false`, as in [these two lines](https://github.com/hrushikeshrv/mjxgui/blob/1c61ba2f85fb436d95162ee0b9013fe8b3601a4f/src/modules/ui.js#L235).

Please feel free to reach out if you need more info or have any questions, thanks!

**Comment by Shivansh175** [comment]
can i also work on it?

**Comment by parthpilkhann** [comment]
Hi @zainbinfurqan @hrushikeshrv is this still in development ? if not, Can i take over?

**Comment by zainbinfurqan** [comment]
> Hi @zainbinfurqan @hrushikeshrv is this still in development ? if not, Can i take over?

yes i am doing it

**Comment by parthpilkhann** [comment]
Alright, @zainbinfurqan thanks for the update.

**Comment by zainbinfurqan** [comment]
@hrushikeshrv  HI, I am little confused on this issue, can you explain a bit more, i have already created a method for hid UI but not sure what to hide.
