### ISSUE TITLE
Text Overflow in Input Editor for Large Equations

### ISSUE THREAD

**Issue by azr-arch** [hrushikeshrv/mjxgui#27]
# Description:

## Bug Report

I’ve encountered a bug in the MJXGUI editor where the text starts to overflow when a large amount of elements are inputted.

## Details

When writing a large equation in the input editor, the text starts to overflow after reaching a max width of around 520px. This results in some parts of the equation being cut off from view, which hampers the user experience.

### Steps to Reproduce

- Open the MJXGUI editor.

- Start inputting a large equation until the width of the equation exceeds around 520px.

- Observe that the text starts to overflow.

## Expected Behavior

The input editor should properly handle large equations and prevent text overflow. This could potentially be achieved by introducing a scroll feature or expanding the width of the input editor as needed.

## Screenshots

![image](https://github.com/hrushikeshrv/mjxgui/assets/79351619/6b6d0a4d-e0ef-4da0-9be2-9527038141d5)

**Comment by hrushikeshrv** [comment]
Thanks for this report @azr-arch 👍🏻 

I think this should be a simple fix. We could change the `max-width` for the `#mjxgui_editor_window` selector to be `min(600px, 90%)` (see [this line in editor.css](https://github.com/hrushikeshrv/mjxgui/blob/1c61ba2f85fb436d95162ee0b9013fe8b3601a4f/src/modules/editor.css#L15)), and add a `overflow-x: auto` property to the `#_mjxgui_editor_display` selector (see [this line in editor.css](https://github.com/hrushikeshrv/mjxgui/blob/1c61ba2f85fb436d95162ee0b9013fe8b3601a4f/src/modules/editor.css#L45)).

I can assign this to you if you'd like.

**Comment by Shivansh175** [comment]
can you please assign this issue to me?

**Comment by hrushikeshrv** [comment]
Hi @Shivansh175, I'm generally assigning issues to whoever reports them, so I'll assign this to Azar. You could claim an unassigned issue if I opened it.

**Comment by azr-arch** [comment]
Okay, assign it, the other one too!

**Comment by hrushikeshrv** [comment]
Hi @azr-arch, I have just merged a PR to simplify the CSS for MJXGUI.  I have removed `editor.css` and the styles in `ui.js`. I have added 2 CSS files - one is at `src/mjxgui.css` and the other is at `docs/css/mjxgui.css`. You can make your changes there. Reach out to me on discord if you have any questions!
