### ISSUE TITLE
Add dark mode support

### ISSUE THREAD

**Issue by hrushikeshrv** [hrushikeshrv/mjxgui#28]
Even though the editor window's CSS can be customized (to be documented according to issue #20), we should add a simple way to switch the editor window's color to a dark theme. 

Maybe this could be done by adding an `options` parameter to the constructor for `MJXGUI` which will take a JSON object containing key value pairs for customizing the MJXGUI editor's behavior, and one of the supported keys could be `theme`.

This fix would need a major version bump.

**Comment by uttej-vsk** [comment]
Hey @hrushikeshrv This is Tej from Discord. I would like to work on this. I have gone through the issue.

**Comment by hrushikeshrv** [comment]
Great, thanks! I'll assign this to you.

**Comment by sricharanandra** [comment]
Is this feature still under development or can I try my hand at it?

**Comment by uttej-vsk** [comment]
> Is this feature still under development or can I try my hand at it?

Hi, I’m working on it.

**Comment by hrushikeshrv** [comment]
Hi @uttej-vsk, what approach are you taking to fix this issue? Since #29 was just fixed, the CSS for the editor is now included separately in `src/mjxgui.css`. Now users will have to link the CSS file on their webpage separately, and the CSS is no longer hardcoded in the `ui.js` file like it used to be.

To add support for dark mode, IMO we should modify the new `src/mjxgui.css` file with the relevant CSS for dark colors, and maybe define variables in the CSS as well.
