### ISSUE TITLE
Include editor CSS as a separate CSS file instead of hardcoding it in ui.js

### ISSUE THREAD

**Issue by hrushikeshrv** [hrushikeshrv/mjxgui#29]
Currently, the CSS for the editor is hardcoded in `ui.js` at [line 203](https://github.com/hrushikeshrv/mjxgui/blob/1c61ba2f85fb436d95162ee0b9013fe8b3601a4f/src/modules/ui.js#L203). Instead, we should provide the CSS file separately, and ask users to include it separately on their page.

This behavior should be documented and will need a major version bump. It should probably be included in the same release as #28.

**Comment by uttej-vsk** [comment]
Hey @hrushikeshrv This is Tej from Discord. I have gone through this. I would like to work on this.

**Comment by hrushikeshrv** [comment]
Hey @sricharanandra, I've already prepared a patch for this, going to create a PR soon.

**Comment by sricharanandra** [comment]
Alright, let me know if something else needs work!
