### ISSUE TITLE
Add to documentation

### ISSUE THREAD

**Issue by hrushikeshrv** [hrushikeshrv/mjxgui#3]
I have a rough version of the documentation that I am working on [here](https://docs.google.com/document/d/1fdf1tIqqZsT5BDz2d8ybv_JcB2XBj_r6bzGmJMHGN9Y/edit?usp=sharing). We need to translate this into HTML to add to the docs at [docs/index.html](https://github.com/hrushikeshrv/mjxgui/blob/main/docs/index.html).

**Comment by LuluNwenyi** [comment]
Hi @hrushikeshrv 

I’d love to have a go at this..

**Comment by hrushikeshrv** [comment]
Great! Currently the docs are structured by section. There is one section tag for each section of the docs (like Installing, Usage, Examples, etc.), and sections like API, Customizing, and Contributing are yet to be translated to HTML. I will be adding to the rough version of the docs (in the Google Doc) in a few hours, then you could follow the same structure that index.html has to translate from Docs to HTML.   

The API section will have 3 sub sections which you could divide however you would like. If you want, you could come up with your own structure for index.html and use that too, if you want to present the page differently than the simple HTML used currently. The stylesheet linked has a few helper classes and variables that could be useful.  

Finally, if you could add syntax highlighting to the code examples, that would be great too, but that would probably require a significant chunk of work. Feel free to ask any questions you have :)

**Comment by LuluNwenyi** [comment]
Hi @hrushikeshrv, I've checked the document and you haven't made the addition. Please let me know when you do this.

**Comment by hrushikeshrv** [comment]
I've added a section right now. I'm holding off for Hacktoberfest to actually start in a few days :)

**Comment by LuluNwenyi** [comment]
Hi @hrushikeshrv ,

Please let me know when the addition is made to a good extent

**Comment by LuluNwenyi** [comment]
Hi @hrushikeshrv, I see you've made additions to the doc. Do you think they're ready to go??

**Comment by hrushikeshrv** [comment]
Yes, the API section is complete. You can add that to the docs. I will be completing the last two sections in the next couple of days.

**Comment by LuluNwenyi** [comment]
Hi @hrushikeshrv I was wondering if this part of the doc is an image

<img width="1393" alt="Screenshot 2021-10-04 at 13 56 33" src="https://user-images.githubusercontent.com/72583144/135855478-c32f4797-a363-4e71-b763-2288ae01c238.png">
e

**Comment by hrushikeshrv** [comment]
It's a diagram that I have inserted, but if you click on edit -> actions, you can download it as an svg

**Comment by LuluNwenyi** [comment]
I think I need to have access to do that.

**Comment by LuluNwenyi** [comment]
@hrushikeshrv I still can't download it💀

**Comment by hrushikeshrv** [comment]
I've sent you an email with the SVG file for it. Let me know it that works for you :)

**Comment by LuluNwenyi** [comment]
Thank you

**Comment by hrushikeshrv** [comment]
@LuluNwenyi any update on the docs?

**Comment by LuluNwenyi** [comment]
Yea, I've pushed some to my forked repo. I'll finish up today and open a PR.

**Comment by hrushikeshrv** [comment]
Sounds good
