### ISSUE TITLE
Adding transitions while scrolling

### ISSUE THREAD

**Issue by Shivansh175** [hrushikeshrv/mjxgui#30]
I think switching between various sections in homepage will look more beautiful with a transitional switch giving it a scroll like effect.

**Comment by sricharanandra** [comment]
By sections you mean "features" "installing" "usage" etc. right? Like add a transition effect for when you click on those links on the navbar?

**Comment by Shivansh175** [comment]
yes! Can i work upon this

**Comment by sricharanandra** [comment]
I have already started setting up my environment to work on this 😅.

**Comment by Shivansh175** [comment]
Aahh...okay🥲 I'm a newbie looking for beginner friendly issues any suggestions for me?

**Comment by sricharanandra** [comment]
There's plenty of sites to look for good first issues like https://www.firsttimersonly.com/. Otherwise searching with "good first issue" tags in repos is the common way

**Comment by saku1331** [comment]
I wish to work on this issue. Kindly assign me this.

**Comment by sricharanandra** [comment]
Feature has already been added. Not sure why this issue is still open. @hrushikeshrv
